[general]

reticulum_host = "dev.reticulum.io"
statsd_host = "localhost:8125"
statsd_prefix = "discordbot."
hubs_hosts = "localhost,hubs.local"
hubs_hook = "Hubs"
shard_id = "0"
shard_count = "0"
verbose = "false"
locale = "en-US"
timezone = "America/Los_Angeles"
